### ISSUE TITLE
URL Shortener

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/awesome-python-projects#12]
Project Details: Are you familiar with some tools like bit.ly and TinyURL ? These tools shorten the URL and makes them easy to remember. Long URLs are filled with difficult characters and it’s not easy to remember them. These services reduces the characters or letters in URLs and returns a new shorten URL to the user.

**Comment by kushal98** [comment]
Hey,

Do we need a script for this or some full stack solution?

Thanks

**Comment by garimasingh128** [comment]
Depends on the level of the participant to which it is assigned! If you can create a web interface or a GUI using tkinter, it would be great. A script would also work okay.

**Comment by kushal98** [comment]
I would like to give a try to script first and later looking into an interfaceapp.
Can u assign this to me?
