### ISSUE TITLE
Pin your note

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/awesome-python-projects#13]
Pin Your Note
Project Details: We get so many ideas throughout the day and it’s a common nature of human that we forget the things very easily (even the important ideas or thoughts) due to our busy schedule or for some other reason. To remember things easily isn’t it a good idea to make an app that create a note of our ideas online? Using Python you can build a Pin Your Note application where a user can list out all the things he/she wants to remember and that list will be accessible from anywhere (since it is on a digital platform).

**Comment by anut123** [comment]
I am going to start my work, please assign to me
