### ISSUE TITLE
Quiz App

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/awesome-python-projects#14]
Quiz Application
Project Details: Quizzes are always helpful in testing the knowledge, identifying the mistakes and correcting those mistakes. Taking an online test is the best way to understand the concepts completely. Using Python you can create a Quiz application that will list out a series of questions for users and the users will be allowed to answer those questions. Think of the Quiz Application as a kind of questionnaire.

**Comment by pranesh-badarinath** [comment]
I am ready to contribute to this issue.

**Comment by pranesh-badarinath** [comment]
Can I proceed like this..
1. The questions will be displayed on the console.
2. user need to answer to that question ( multiple choice question)
3. Finally after completion of the quiz result will gona display..

**Comment by garimasingh128** [comment]
Yeah. After the quiz ends, display his/her score along with the correct answers just like how Google forms does in the quiz section. You can take sample questions by yourself. If you want, Create a simple GUI using tkinter. It's quite easy and looks simple.

**Comment by pranesh-badarinath** [comment]
Sure, I ll try my best...
Thank you

**Comment by pranesh-badarinath** [comment]
@garimasingh128  
This issue also successfully merged into the main repo.
Thank you
