### ISSUE TITLE
File renaming tool

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/awesome-python-projects#16]
File Renaming Tool
Project Details: A lot of time we need to rename the files in our directory according to certain conventions. For example, File001.jpg, File002.jpg, File003.jpg, and this goes on. Doing this task manually can be repetitive and boring. To avoid this manual work, you can create a tool to rename a large number of files.

**Comment by ViAsmit** [comment]
I would like to work on the project.
Will You Please assigned this to me?
@garimasingh128 @mrinal41298
