### ISSUE TITLE
Contact book

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/awesome-python-projects#17]
Everyone uses a contact book to save contact details, including name, address, phone number, and even email address. This is a command-line project where you will design a contact book application that users can use to save and find contact details. The application should also allow users to update contact information, delete contacts, and list saved contacts. The SQLite database is the ideal platform for saving contacts.

**Comment by anut123** [comment]
I am going to start my work, please assign to me

**Comment by garimasingh128** [comment]
@anut123  Hope any other issue is not assigned to you as of now for which you have not created a PR. If yes, unassign from any one.

**Comment by anut123** [comment]
we have to do with Sqlite database so should we have to install any software for Sqlite database or in Pycharm we can do it?

**Comment by garimasingh128** [comment]
I believe that you have to install the sqlite software to connect to database.

**Comment by anut123** [comment]
okay ma'am.
