### ISSUE TITLE
Notification app

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/awesome-python-projects#18]
Have you ever wondered how notifications work? This small python project idea will throw some light on this. The desktop notifier apps run on your system and send you a piece of information after a fixed interval of time. We suggest you use libraries such as notify2, requests, etc. to build such a program.

**Comment by anut123** [comment]
I am going to start my work, please assign to me

**Comment by anut123** [comment]
I am going to start my work, please assign to me

**Comment by garimasingh128** [comment]
All the best. :)

**Comment by anut123** [comment]
Thankyou ma'am

**Comment by anut123** [comment]
Okay ma'am
