### ISSUE TITLE
Rock paper scissors game

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/awesome-python-projects#3]
Rock, Paper, Scissors Game
Make a rock-paper-scissors game where it is the player vs the computer. The computer’s answer will be randomly generated, while the program will ask the user for their input. This project will better your understanding of while loops and if statements.

**Comment by pranesh-badarinath** [comment]
I am ready to contribute to this issue.

**Comment by Gomathi-P** [comment]
I am ready to work with this issue

**Comment by garimasingh128** [comment]
> I am ready to work with this issue

Already assigned to @pranesh-badarinath

**Comment by siddeshshewde** [comment]
@garimasingh128 I want to try this. Is @pranesh-badarinath still working on it?

**Comment by garimasingh128** [comment]
@pranesh-badarinath did u create a PR for this?

**Comment by pranesh-badarinath** [comment]
@garimasingh128  I have completed this issue long back , This issue is already merged to your main repo

**Comment by garimasingh128** [comment]
Cool. Please mention the issue no in the PR description otherwise solved issues remain open even if the PR is merged. :)

**Comment by pranesh-badarinath** [comment]
sure
