### ISSUE TITLE
Generating a sine vs cosine curve

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/awesome-python-projects#4]
Generating a sine vs cosine curve
For this project, you will have a generate a sine vs cosine curve. You will need to use the numpy library to access the sine and cosine functions. You will also need to use the matplotlib library to draw the curve. To make this more difficult, make the graph go from -360° to 360°, with there being a 180° difference between each point on the x-axis.

**Comment by kushal98** [comment]
Hey,

I would like to work on this.

Thanks

**Comment by garimasingh128** [comment]
Please keep in mind the next time you create a PR, you get the issue assigned to yourself first. Nevertheless, we'll review it.

**Comment by kushal98** [comment]
Sure will take care from next time.
