### ISSUE TITLE
Iris Flowers Classification Projectiris flower classification using machine learning

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/awesome-python-projects#49]
Iris Flowers Classification Projectiris flower classification using machine learning
Project idea – The iris flowers have different species and you can distinguish them based on the length of petals and sepals. This is a basic project for machine learning beginners to predict the species of a new iris flower.

https://archive.ics.uci.edu/ml/datasets/Iris

**Comment by Diu2912** [comment]
I want to start working on this please assign to me...
