### ISSUE TITLE
Typing Speed Test

### ISSUE THREAD

**Issue by mrinal41298** [garimasingh128/awesome-python-projects#8]
A python game where you are given a statement and type it in the text field. Calculate datas such as typing speed, accuracy and more if you want to.

**Comment by anut123** [comment]
I am going to start my work, please assign to me

**Comment by garimasingh128** [comment]
Create a PR for Issue #9 first. Then ask to be assigned to another!

**Comment by anut123** [comment]
I am going to start my work, please assign to me

**Comment by anut123** [comment]
Typing Speed Test issue is been completed , merged , issue is also mentioned in the PR description but how to closed these issue?

**Comment by garimasingh128** [comment]
Mention in the PR description like Fixes #8

**Comment by anut123** [comment]
i didn't get

**Comment by anut123** [comment]
I didnot get it can you explain it once again

**Comment by anut123** [comment]
I did not get it can you please explain it once again.

**Comment by garimasingh128** [comment]
In the PR description, you have left it blank. You can mention like it fixes issue #8 for example. Or if you know that your PR is merged then you can close the issue yourself or comment on the issue that this has been resolved by PR #4 for example.

**Comment by anut123** [comment]
PR is merged then where is the option of close the issue

**Comment by garimasingh128** [comment]
You would only get the option of close issue if you have created that issue. Otherwise, just comment and I'll close it myself.
