### ISSUE TITLE
ROCK_PAPER_SCISSOR

### ISSUE THREAD

**Issue by das-kingdom** [garimasingh128/awesome-python-projects#84]
There is a small issue in the first lines of the code
https://github.com/garimasingh128/awesome-python-projects/blob/master/ROCK_PAPER_SCISSOR/GAME.PY

**Reproduce**
Run the program. 
It will say "Enter 1 to play 0 to exit"
Here we can actually enter anything other than 0 to play

**Expected behavior**
It should return error if we enter anything other than 1 or 0

**Comment by anubhab-code** [comment]
I can fix this, can I be assigned to this?
