### ISSUE TITLE
Secure Your Password

### ISSUE THREAD

**Issue by mrinal41298** [garimasingh128/awesome-python-projects#9]
A project where we input a string and it returns a pattern consisting of symbols to secure our password. You can have your own criteria for pattern generation i.e., let's say for 'a' it generates '!!'

**Comment by anut123** [comment]
I am going to start my work, please assign to me

**Comment by anut123** [comment]
I am going to start my work, please assign to me

**Comment by siddeshshewde** [comment]
Is anyone still working on this?

**Comment by garimasingh128** [comment]
@anut123 did u create a PR for this?

**Comment by anut123** [comment]
Secure your password issue is been completed and merged also.

**Comment by garimasingh128** [comment]
Cool. Please mention the issue in the PR description otherwise solved issues remain open. :)

**Comment by anut123** [comment]
Okay ma'am

**Comment by anut123** [comment]
what should i mention in the PR description?

**Comment by anut123** [comment]
completed issue in the PR description.

**Comment by anut123** [comment]
Mentioned the issue in the PR description also.

**Comment by anut123** [comment]
just now mention the issue in the PR description.
